- name: config > Template
  template:
    src:  "{{ elao_mailcatcher_config_template|ternary(elao_mailcatcher_config_template, 'config/empty.j2') }}"
    dest: "{{ elao_mailcatcher_config_file }}"
  when: (elao_mailcatcher_config_template is not none) or (elao_mailcatcher_config|length)
  notify:
    - mailcatcher restart
