---

- name: install > Packages dependencies
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - ruby-dev
    - libsqlite3-dev

- name: install > Gem i18n dependency
  gem:
    name: i18n
    version: 0.6.11
    state: present
    user_install: no

- name: install > Package
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - mailcatcher
